config/routes.rb
YuetaiWendycanOrg::Application.routes.draw do
  devise_for :users

  root 'site#index'
  get 'site/random'

  get 'dashboard/index', as: :dashboard

  get 'articles/feed' => 'articles#feed'

  resources :articles, only: [:index, :show]
  resources :tags, only: [:index, :show]
  resources :presentation, only: [:index, :show]

  get 'series/index'
  get 'series/show'

  resources :users do
    resources :notebooks, only: [:index, :show]
  end

  mount Api => '/api/'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :body, :title, :tag_list, :template, :language

  belongs_to :user

  has_many :taggings
  has_many :tags, through: :taggings

  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :template, presence: true, inclusion: { in: ['blog', 'series', 'presentation'] }
  validates :language, inclusion: { in: ['html', 'markdown', 'simditor']}

  # before_save :set_node
  scope :recent, ->(num) { order('created_at DESC').limit(num) }
  # def set_node
  #   tag = Node.find_by_name(self.utag)
  #   if tag.nil?
  #     tag = Node.find_by_id(self.node_id)
  #   end
  #   author = Author.find_by_name(self.uauthor)
  #   if author.nil?
  #     author = Author.find_by_id(self.author_id)
  #   end
  #   self.node = tag
  #   self.author = author
  # end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :notebook
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
    belongs_to :user
    has_many :notes
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  before_create :generate_authentication_token

  has_many :articles
  has_many :comments
  has_many :notebooks
  has_many :notes

  def update_user_words_count
    count = 0
    self.articles.where(template: 'blog').each do |article|
      count += HTML::FullSanitizer.new.sanitize(article.body).length
    end
    self.words_count = count
  end

  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.hex 20
      break unless self.class.exists?(authentication_token: authentication_token)
    end
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  layout 'article', :only => [:index, :show]

  def index
    @user = User.find_by_id(params[:user_id])
    @articles = @user.notebooks.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @user = User.find_by_id(params[:user_id])
    @notebook = @user.notebooks.find_by_id(params[:id])
    @articles = @notebook.notes.paginate(:page => params[:page], :per_page => 10)
  end
end

def format_date(date)
  return date.to_s.split(' UTC')[0]
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'application', :only => [:random]

  def index
  end

  def random
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chap_helper.rb
module ChapHelper
end

app/helpers/chaps_helper.rb
module ChapsHelper
end

app/helpers/excerpts_helper.rb
module ExcerptsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/notebooks/index.html.haml
= content_for :title, '读书笔记 · 阅台 · 记录想法 分享点滴'
= render "layouts/user_sidebar"

.notebooks-wrap
  .notebooks
    - @articles.each_with_index do |item, i|
      .notebook
        %h4
          = link_to user_notebook_path(id: item.id) do
            = item.title
          %p
            = item.authors
            %small= item.citation.split(':')[1]
        .meta
          %p
            = link_to user_path(id: @user.id), class: 'author-name' do
              = item.user.username
            %span 创建于
            = format_date item.created_at
            %span ，上次更新于
            = format_date item.updated_at
            %span ，共
            = item.notes.length
            %span 条笔记
      - if i < @articles.length - 1
        %hr

  = render "layouts/pager"

app/views/notebooks/show.html.haml
= content_for :title, @notebook.title + ' · 阅台 · 记录想法 分享点滴'
= render "layouts/user_sidebar"

.notebooks-wrap
  .notebook
    %h4
      = @notebook.title
      %p
        = @notebook.authors
        %small= @notebook.citation.split(':')[1]
    .meta
      %p
        = link_to user_path(id: @user.id), class: 'author-name' do
          = @notebook.user.username
        %span 创建于
        = format_date @notebook.created_at
        %span ，上次更新于
        = format_date @notebook.updated_at
        %span ，共
        = @notebook.notes.length
        %span 条笔记
    %hr
    .book-notes
      - @articles.each_with_index do |item, i|
        .book-note
          %h4= item.section
          - if item.section
            %hr
          %p.location
            第
            = item.location
            页
          - if item.content_type == 'note'
            %p.note= item.content
          - else
            %p.content= item.content
          - if !item.note.empty?
            %p.note= item.note

= render "layouts/pager"