config/routes.rb
YuetaiWendycanOrg::Application.routes.draw do
  devise_for :users

  root 'site#index'
  get 'site/random'

  get 'dashboard/index', as: :dashboard

  get 'articles/feed' => 'articles#feed'

  resources :articles, only: [:index, :show]
  resources :tags, only: [:index, :show]
  resources :presentation, only: [:index, :show]

  get 'series/index'
  get 'series/show'

  resources :users do
    resources :notebooks, only: [:index, :show]
  end

  mount Api => '/api/'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :body, :title, :tag_list, :template, :language

  belongs_to :user

  has_many :taggings
  has_many :tags, through: :taggings

  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :template, presence: true, inclusion: { in: ['blog', 'series', 'presentation'] }
  validates :language, inclusion: { in: ['html', 'markdown', 'simditor']}

  # before_save :set_node
  scope :recent, ->(num) { order('created_at DESC').limit(num) }
  # def set_node
  #   tag = Node.find_by_name(self.utag)
  #   if tag.nil?
  #     tag = Node.find_by_id(self.node_id)
  #   end
  #   author = Author.find_by_name(self.uauthor)
  #   if author.nil?
  #     author = Author.find_by_id(self.author_id)
  #   end
  #   self.node = tag
  #   self.author = author
  # end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :notebook
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
    belongs_to :user
    has_many :notes
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  before_create :generate_authentication_token

  has_many :articles
  has_many :comments
  has_many :notebooks
  has_many :notes

  def update_user_words_count
    count = 0
    self.articles.where(template: 'blog').each do |article|
      count += HTML::FullSanitizer.new.sanitize(article.body).length
    end
    self.words_count = count
  end

  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.hex 20
      break unless self.class.exists?(authentication_token: authentication_token)
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'application', :only => [:random]

  def index
  end

  def random
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout 'article', :only => [:show]

  def show
    @tag = Tag.find_by_id(params[:id])
    @tags = Tag.joins('LEFT JOIN (select count(id) alength, tag_id from taggings a group by a.tag_id ) ac on ac.tag_id = tags.id').order('ac.alength desc')
    @authors = User.joins('JOIN (select count(id) alength, user_id from articles a group by a.user_id ) ac on ac.user_id = users.id').order('ac.alength desc').limit(5)
    @articles = @tag.articles.order('created_at DESC')
      .where(template: 'blog').paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chap_helper.rb
module ChapHelper
end

app/helpers/chaps_helper.rb
module ChapsHelper
end

app/helpers/excerpts_helper.rb
module ExcerptsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/tags/show.html.haml
#main-content.articles-wrap
  .sidebar.pull-left.hide-for-small-only
    .hot-tags.tags
      - @tags.each do |tag|
        - if tag.id == @tag.id
          = link_to 'javascript:;', class: 'tag', id: tag.id do
            %span.label.round= tag.name
        - else
          = link_to tag_path(tag.id), class: 'tag', id: tag.id do
            %span.label.round= tag.name
    .hot-authors
      %table
        %thead
          %tr
            %th 作者
            %th 文章
            %th 字数
        %tbody
          - @authors.each do |author|
            %tr
              %td
                = link_to author do
                  = author.username
              %td= author.articles.length
              %td
                = (author.words_count/10000).to_s + '.' + (author.words_count%10000/100).to_s + '万'
  .tag-info{:'data-id' => @tag.id}
    %span.tag-name= @tag.name
    - if @tag.articles.length < 1
      暂无博客
    - else
      已有
      %span.tag-sum= @tag.articles.length
      篇博客
    创建于
    %span.tag-date= @tag.created_at.strftime("%Y.%m.%d")

  #y-articles.articles
    .loading
      %i.fa.fa-spinner.fa-spin

  = render "layouts/pager"

= render "layouts/article"

- blogs_json = render template: "articles/index", formats: [:json], handlers: [:jbuilder]

= content_for :js_ext do
  :javascript
    $(document).ready(function () {
      var blogs_view = new Yuetai.Views.Blogs.BlogsView(#{blogs_json});
    });
    $('.articles-btn').addClass('active');
    var tagId = $('.tag-info').data('id');
    if(tagId >= 0) {
      $('.tag#' + tagId).addClass('active');
    }

= content_for :title, '阅台 · 记录想法 分享点滴'