config/routes.rb
YuetaiWendycanOrg::Application.routes.draw do
  devise_for :users

  root 'site#index'
  get 'site/random'

  get 'dashboard/index', as: :dashboard

  get 'articles/feed' => 'articles#feed'

  resources :articles, only: [:index, :show]
  resources :tags, only: [:index, :show]
  resources :presentation, only: [:index, :show]

  get 'series/index'
  get 'series/show'

  resources :users do
    resources :notebooks, only: [:index, :show]
  end

  mount Api => '/api/'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :body, :title, :tag_list, :template, :language

  belongs_to :user

  has_many :taggings
  has_many :tags, through: :taggings

  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :template, presence: true, inclusion: { in: ['blog', 'series', 'presentation'] }
  validates :language, inclusion: { in: ['html', 'markdown', 'simditor']}

  # before_save :set_node
  scope :recent, ->(num) { order('created_at DESC').limit(num) }
  # def set_node
  #   tag = Node.find_by_name(self.utag)
  #   if tag.nil?
  #     tag = Node.find_by_id(self.node_id)
  #   end
  #   author = Author.find_by_name(self.uauthor)
  #   if author.nil?
  #     author = Author.find_by_id(self.author_id)
  #   end
  #   self.node = tag
  #   self.author = author
  # end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :notebook
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
    belongs_to :user
    has_many :notes
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  before_create :generate_authentication_token

  has_many :articles
  has_many :comments
  has_many :notebooks
  has_many :notes

  def update_user_words_count
    count = 0
    self.articles.where(template: 'blog').each do |article|
      count += HTML::FullSanitizer.new.sanitize(article.body).length
    end
    self.words_count = count
  end

  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.hex 20
      break unless self.class.exists?(authentication_token: authentication_token)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chap_helper.rb
module ChapHelper
end

app/helpers/chaps_helper.rb
module ChapsHelper
end

app/helpers/excerpts_helper.rb
module ExcerptsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_article.html.haml
%script{type: 'text/template', id: 't-blog'}
  .article{:'data-id' => '{{= blog.id }}'}
    %h4
      %a{:href => "/articles/{{= blog.id }}" }
        {{= blog.title }}
    .article-meta
      %p
        %a.article-author-name {{= blog.username}}
        %span.article-date {{= blog.date}}
        %strong {{= blog.visited_count}}
        %span 次阅读
      %p.tag-list {{= blog.tag_list }}
    .article-body
      %p {{= blog.body }}
    %hr

app/views/layouts/_footer.html.haml
.row.text-center
  .row
    .large-12.columns.small-8.small-centered
      .row
        .large-12.columns
          %h5 记录想法， 分享点滴
      %h5
        %small by
        = link_to "wendy", "https://github.com/wendycan"

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Uncomment to make IE8 render like IE7
-# meta http-equiv="X-UA-Compatible" content="IE=7"

-# Set the viewport width to device width for mobile
%meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
%meta{ name: "fragment", content: "!"}

%title= content_for?(:title) ? yield(:title) : "阅台"

= stylesheet_link_tag "application"
= javascript_include_tag "vendor/modernizr"
= csrf_meta_tag

:javascript
  // google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54778589-1', 'auto');
  ga('send', 'pageview', {
   'page': location.pathname + location.search  + location.hash
  });

app/views/layouts/_js.html.haml
= javascript_include_tag "application"
= yield(:js_common)
= yield(:js_ext)

app/views/layouts/_nav.html.haml
.hide-for-small-only
  %nav.y-nav.clearfix
    %ul.left
      %li
        = link_to '/articles' do
          = image_tag('logo.png')
    %ul.right
      %li
        = link_to articles_path do
          %i.fa.fa-file-text-o
          博客
      %li
        = link_to presentation_index_path do
          %i.fa.fa-caret-square-o-right
          演示文稿
      - if user_signed_in?
        %li.nav-user-btn
          %a{:href => '#'}
            %i.fa.fa-user
            = current_user.username
            %i.fa.fa-angle-down
          %ul.children-nav
            - if current_user.level > 0
              %li
                %a{:href => '/dashboard/index#blogs'}
                  %i.fa.fa-file-text-o
                  我的博客
              %li
                %a{:href => '/dashboard/index#notebooks'}
                  %i.fa.fa-book
                  我的笔记书
              %li
                %a{:href => '/dashboard/index#presentations'}
                  %i.fa.fa-caret-square-o-right
                  我的演示文稿
              %li
                = link_to user_path(current_user) do
                  %i.fa.fa-file-text-o
                  我的主页
              %li
                %a{:href => '/dashboard/index#settings'}
                  %i.fa.fa-wrench
                  设置
            / %li
            /   %a{:href => '/site/random'}
            /     %i.fa.fa-magic
            /     随便看看
            - if current_user.level > 1
              %li
                %a{:href => '/dashboard/index#manage/articles'}
                  %i.fa.fa-user-secret
                  管理
            %li
              %a#logout-btn{:href => '#'}
                %i.fa.fa-sign-out
                退出
      - else
        %li
          = link_to new_user_session_path do
            %i.fa.fa-sign-in
            登录
        %li
          = link_to new_user_registration_path do
            %i.fa.fa-arrow-right
            注册


= content_for :js_common do
  :javascript
    $('#logout-btn').click(function(){
      alertify.confirm('您确定从阅台登出？', function (e) {
        if (e) {
          // user clicked 'ok'
          $.ajax({
            url: '/users/sign_out',
            type: 'DELETE',
            success: function () {
              window.location.href = '/';
            }
          });
        } else {
            // user clicked 'cancel'
            alertify.success('您刚刚取消了登出。');
        }
      });
    });

app/views/layouts/_pager.html.haml
- records ||= @articles
- params.delete(:show_joke_point)
- if records && records.total_pages > 1
  - total_pages = [records.total_pages,1000].min
  .pager
    %ul
      %li.pager-sum 共 #{total_pages} 页
      - l = records.current_page - 2
      - r = records.current_page + 2
      - if records.previous_page
        %li.pager-nav-btn.pager-prev
          = link_to(params.merge(:page => records.previous_page), {:class => 'prev'}) do
            上一页
      - if records.current_page == 1
        %li.pager-nav-btn.active 1
      - else
        %li.pager-nav-btn= link_to '1', params.merge(:page => 1)
      - if l > 2
        %li …
      - else l = 2
      - l.upto([r,total_pages - 1].min) do |i|
        - if i == records.current_page
          %li.pager-nav-btn.active= i
        - else
          %li.pager-nav-btn= link_to i, params.merge(:page => i)
      - if r < total_pages - 1
        %li …
      - if records.current_page == total_pages
        %li.pager-nav-btn.active= total_pages
      - else
        %li.pager-nav-btn= link_to total_pages, params.merge({:page => total_pages})
      - if records.next_page
        %li.pager-nav-btn.pager-next
          = link_to '下一页', params.merge(:page => records.next_page), {:class => "next"}
      - if total_pages > 1
        %li.pager-skip.hide-for-small-only
          %form.pager-skip-form
            %input{:type => "text"}
            %button{:type => "submit"} 跳页

= content_for :js_ext do
  :javascript
    $(document).ready(function () {
      $('.pager-skip-form').on('submit', function (e) {
        e.preventDefault();
        var page_num = $.trim($(this).find('input').val());
        if (page_num) {
          var href = $('.pager .pager-next a').attr('href') || $('.pager .pager-prev a').attr('href');
          if (href) {
            if (href.match(/page=/)) {
              window.location.href = href.replace(/page=\d+/, "page=" + page_num);
            }
          }
        }
      });
    });

app/views/layouts/_small_nav.html.haml
%nav.tab-bar.show-for-small-only#small-nav
  %section.left-small.text-center
    %a.left-off-canvas-toggle.menu-icon
      %span
  %section.middle.tab-bar-section
    %h1.title 阅台

%aside.left-off-canvas-menu
  %ul.off-canvas-list.small-nav
    %li.index.text-left
      %a{:href => '/'}
        = image_tag 'home.png'
        %span 阅台
    %li.articles.text-left
      %a{:href => '/articles'}
        = image_tag 'blog.png'
        %span 博客
    %li.books.text-left
      %a{:href => '/presentation'}
        = image_tag 'presentation.png'
        %span 演示文稿
    %li.text-left
      %a{:href => "/site/random"}
        = image_tag 'random.png'
        随便看看
    /%li.authors
    /  %a{:href => '#authors'}
    /    = image_tag 'author-white.png'
    /    %span 作者
    / %li.about
    /   %a.reverse{:href => "http://weibo.com/u/3260368113/home?wvr=5"}
    /     %i.fa.fa-weibo
    /   %a.reverse{:href => "https://github.com/wendycan"}
    /     %i.fa.fa-github
    /   %a.reverse{:href => "https://bitbucket.org/wendycan"}
    /     %i.fa.fa-bitbucket
    /   %a.reverse{:href => "mailto:wendy@larklearning.com"}
    /     %i.fa.fa-envelope

app/views/layouts/_user_sidebar.html.haml
.sidebar.pull-left.hide-for-small-only
  .author-summary
    = link_to @user do
      = image_tag @user.avator
    %h5
      = link_to @user do
        - if @user.username.blank?
          匿名
        - else
          = @user.username
    .author-count
      %p
        = link_to @user do
          文章
          %strong= @user.articles.length
          篇
      %p
        = link_to user_notebooks_path(user_id: @user.id) do
          笔记书
          %strong= @user.notebooks.length
          本
      %p.words-count
        %span
          总
          %strong#user-word-count= @user.words_count
          字
    %p= @user.desc
    .author-links
      = mail_to @user.email do
        %i.fa.fa-envelope
      = link_to @user.github do
        %i.fa.fa-github
      %a.author-webchat{:href => 'javascript:;'}
        %i.fa.fa-weixin
        = image_tag(@user.webchat)

app/views/layouts/application.html.haml
!!!5
%head
  = render :partial => 'layouts/head'
%body
  .off-canvas-wrap{:'data-offcanvas' => true}
    .inner-wrap
      = render :partial => 'layouts/nav'
      = render :partial => 'layouts/small_nav'
      - if !notice.nil?
        .alert-box.success{:'data-alert' => true}
          = notice
          %a.close{:href => "#"} &times;
      - if !alert.nil?
        .alert-box.alert{:'data-alert' => true}
          = alert
          %a.close{:href => "#"} &times;
      .not-footer
        = yield
      .footer
        = render :partial => 'layouts/footer'
      .exit-off-canvas

  = render 'layouts/js'

app/views/layouts/article.html.haml
!!!5
%head
  = render :partial => 'layouts/head'
%body
  .off-canvas-wrap{:'data-offcanvas' => true}
    .inner-wrap
      = render :partial => 'layouts/nav'
      = render :partial => 'layouts/small_nav'
      .not-footer.article-layout
        .container
          - if !notice.nil?
            .alert-box.success{:'data-alert' => true}
              = notice
              %a.close{:href => "#"} &times;
          - if !alert.nil?
            .alert-box.alert{:'data-alert' => true}
              = alert
            %a.close{:href => "#"} &times;
          = yield
      .footer
        = render :partial => 'layouts/footer'
      .exit-off-canvas

  = render 'layouts/js'

app/views/layouts/dashboard.html.haml
!!!5
%head
  = render :partial => 'layouts/head'
%body
  .off-canvas-wrap{:'data-offcanvas' => true}
    .inner-wrap
      = render :partial => 'layouts/nav'
      = render :partial => 'layouts/small_nav'
      .hide
        = if !notice.nil?
          %p.notice= notice
        = if !alert.nil?
          %p.alert= alert
      .not-footer
        = yield
      .footer
        = render :partial => 'layouts/footer'
      .exit-off-canvas

  = javascript_include_tag "app-dash"
  = yield(:js_common)
  = yield(:js_ext)

app/views/layouts/site.html.haml
!!!5
%head
  = render :partial => 'layouts/head'
%body.home
  .off-canvas-wrap{:'data-offcanvas' => true}
    .inner-wrap
      .hide
        = if !notice.nil?
          %p.notice= notice
        = if !alert.nil?
          %p.alert= alert
      .not-footer
        = yield
      .exit-off-canvas

  = render 'layouts/js'